// Generated by gencpp from file ed_gui_server/Color.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_COLOR_H
#define ED_GUI_SERVER_MESSAGE_COLOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ed_gui_server
{
template <class ContainerAllocator>
struct Color_
{
  typedef Color_<ContainerAllocator> Type;

  Color_()
    : r(0)
    , g(0)
    , b(0)
    , a(0)  {
    }
  Color_(const ContainerAllocator& _alloc)
    : r(0)
    , g(0)
    , b(0)
    , a(0)  {
  (void)_alloc;
    }



   typedef uint8_t _r_type;
  _r_type r;

   typedef uint8_t _g_type;
  _g_type g;

   typedef uint8_t _b_type;
  _b_type b;

   typedef uint8_t _a_type;
  _a_type a;





  typedef boost::shared_ptr< ::ed_gui_server::Color_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ed_gui_server::Color_<ContainerAllocator> const> ConstPtr;

}; // struct Color_

typedef ::ed_gui_server::Color_<std::allocator<void> > Color;

typedef boost::shared_ptr< ::ed_gui_server::Color > ColorPtr;
typedef boost::shared_ptr< ::ed_gui_server::Color const> ColorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ed_gui_server::Color_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ed_gui_server::Color_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ed_gui_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ed_gui_server': ['/home/gosse/ropod-project-software/catkin_workspace/src/functionalities/ED/ed_gui_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::Color_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::Color_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::Color_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::Color_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::Color_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::Color_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ed_gui_server::Color_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a89b17adab5bedef0b554f03235d9b3";
  }

  static const char* value(const ::ed_gui_server::Color_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a89b17adab5bedeULL;
  static const uint64_t static_value2 = 0xf0b554f03235d9b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ed_gui_server::Color_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed_gui_server/Color";
  }

  static const char* value(const ::ed_gui_server::Color_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ed_gui_server::Color_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 r\n\
uint8 g\n\
uint8 b\n\
uint8 a\n\
";
  }

  static const char* value(const ::ed_gui_server::Color_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ed_gui_server::Color_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
      stream.next(m.a);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Color_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ed_gui_server::Color_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ed_gui_server::Color_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.r);
    s << indent << "g: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.g);
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
    s << indent << "a: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.a);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_COLOR_H
