// Generated by gencpp from file ed_gui_server/EntityMeshAndAreas.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_ENTITYMESHANDAREAS_H
#define ED_GUI_SERVER_MESSAGE_ENTITYMESHANDAREAS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ed_gui_server/Mesh.h>
#include <ed_gui_server/Area.h>

namespace ed_gui_server
{
template <class ContainerAllocator>
struct EntityMeshAndAreas_
{
  typedef EntityMeshAndAreas_<ContainerAllocator> Type;

  EntityMeshAndAreas_()
    : id()
    , mesh()
    , areas()  {
    }
  EntityMeshAndAreas_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , mesh(_alloc)
    , areas(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef  ::ed_gui_server::Mesh_<ContainerAllocator>  _mesh_type;
  _mesh_type mesh;

   typedef std::vector< ::ed_gui_server::Area_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ed_gui_server::Area_<ContainerAllocator> >::other >  _areas_type;
  _areas_type areas;





  typedef boost::shared_ptr< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> const> ConstPtr;

}; // struct EntityMeshAndAreas_

typedef ::ed_gui_server::EntityMeshAndAreas_<std::allocator<void> > EntityMeshAndAreas;

typedef boost::shared_ptr< ::ed_gui_server::EntityMeshAndAreas > EntityMeshAndAreasPtr;
typedef boost::shared_ptr< ::ed_gui_server::EntityMeshAndAreas const> EntityMeshAndAreasConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ed_gui_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ed_gui_server': ['/home/gosse/ropod-project-software/catkin_workspace/src/functionalities/ED/ed_gui_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a80443db3b17cc4bd6acd81c33c8aba2";
  }

  static const char* value(const ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa80443db3b17cc4bULL;
  static const uint64_t static_value2 = 0xd6acd81c33c8aba2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed_gui_server/EntityMeshAndAreas";
  }

  static const char* value(const ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n\
Mesh mesh\n\
Area[] areas\n\
\n\
================================================================================\n\
MSG: ed_gui_server/Mesh\n\
# Mesh identifier\n\
uint32 revision\n\
\n\
# At the moment, only vertices are used. The triangles are described by 9 elements in the\n\
# vertices array (x1, y1, z1, x2, y2, z2, x3, y3, z3). The triangles array is NOT used.\n\
\n\
# (original method (NOT USED): List of vertices: each 3 elements describe (x, y, z) )\n\
float32[] vertices\n\
\n\
# (origin method (NOT USED) List of indices: each 3 indices describe one triangle, indexing the vertices given above)\n\
uint32[] triangles\n\
\n\
================================================================================\n\
MSG: ed_gui_server/Area\n\
string name\n\
Mesh mesh\n\
";
  }

  static const char* value(const ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.mesh);
      stream.next(m.areas);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EntityMeshAndAreas_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "mesh: ";
    s << std::endl;
    Printer< ::ed_gui_server::Mesh_<ContainerAllocator> >::stream(s, indent + "  ", v.mesh);
    s << indent << "areas[]" << std::endl;
    for (size_t i = 0; i < v.areas.size(); ++i)
    {
      s << indent << "  areas[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ed_gui_server::Area_<ContainerAllocator> >::stream(s, indent + "    ", v.areas[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_ENTITYMESHANDAREAS_H
