// Generated by gencpp from file ed_gui_server/GetEntityInfo.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_GETENTITYINFO_H
#define ED_GUI_SERVER_MESSAGE_GETENTITYINFO_H

#include <ros/service_traits.h>


#include <ed_gui_server/GetEntityInfoRequest.h>
#include <ed_gui_server/GetEntityInfoResponse.h>


namespace ed_gui_server
{

struct GetEntityInfo
{

typedef GetEntityInfoRequest Request;
typedef GetEntityInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEntityInfo
} // namespace ed_gui_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ed_gui_server::GetEntityInfo > {
  static const char* value()
  {
    return "2e1719924b71d4aa94abbfdae6b460c8";
  }

  static const char* value(const ::ed_gui_server::GetEntityInfo&) { return value(); }
};

template<>
struct DataType< ::ed_gui_server::GetEntityInfo > {
  static const char* value()
  {
    return "ed_gui_server/GetEntityInfo";
  }

  static const char* value(const ::ed_gui_server::GetEntityInfo&) { return value(); }
};


// service_traits::MD5Sum< ::ed_gui_server::GetEntityInfoRequest> should match 
// service_traits::MD5Sum< ::ed_gui_server::GetEntityInfo > 
template<>
struct MD5Sum< ::ed_gui_server::GetEntityInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ed_gui_server::GetEntityInfo >::value();
  }
  static const char* value(const ::ed_gui_server::GetEntityInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ed_gui_server::GetEntityInfoRequest> should match 
// service_traits::DataType< ::ed_gui_server::GetEntityInfo > 
template<>
struct DataType< ::ed_gui_server::GetEntityInfoRequest>
{
  static const char* value()
  {
    return DataType< ::ed_gui_server::GetEntityInfo >::value();
  }
  static const char* value(const ::ed_gui_server::GetEntityInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ed_gui_server::GetEntityInfoResponse> should match 
// service_traits::MD5Sum< ::ed_gui_server::GetEntityInfo > 
template<>
struct MD5Sum< ::ed_gui_server::GetEntityInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ed_gui_server::GetEntityInfo >::value();
  }
  static const char* value(const ::ed_gui_server::GetEntityInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ed_gui_server::GetEntityInfoResponse> should match 
// service_traits::DataType< ::ed_gui_server::GetEntityInfo > 
template<>
struct DataType< ::ed_gui_server::GetEntityInfoResponse>
{
  static const char* value()
  {
    return DataType< ::ed_gui_server::GetEntityInfo >::value();
  }
  static const char* value(const ::ed_gui_server::GetEntityInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_GETENTITYINFO_H
