// Generated by gencpp from file ed_gui_server/GetEntityInfoRequest.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_GETENTITYINFOREQUEST_H
#define ED_GUI_SERVER_MESSAGE_GETENTITYINFOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ed_gui_server
{
template <class ContainerAllocator>
struct GetEntityInfoRequest_
{
  typedef GetEntityInfoRequest_<ContainerAllocator> Type;

  GetEntityInfoRequest_()
    : id()
    , measurement_image_border(0)  {
    }
  GetEntityInfoRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , measurement_image_border(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef int32_t _measurement_image_border_type;
  _measurement_image_border_type measurement_image_border;





  typedef boost::shared_ptr< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetEntityInfoRequest_

typedef ::ed_gui_server::GetEntityInfoRequest_<std::allocator<void> > GetEntityInfoRequest;

typedef boost::shared_ptr< ::ed_gui_server::GetEntityInfoRequest > GetEntityInfoRequestPtr;
typedef boost::shared_ptr< ::ed_gui_server::GetEntityInfoRequest const> GetEntityInfoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ed_gui_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ed_gui_server': ['/home/gosse/ropod-project-software/catkin_workspace/src/functionalities/ED/ed_gui_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5be0f281839df79090682cdf8e62944b";
  }

  static const char* value(const ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5be0f281839df790ULL;
  static const uint64_t static_value2 = 0x90682cdf8e62944bULL;
};

template<class ContainerAllocator>
struct DataType< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed_gui_server/GetEntityInfoRequest";
  }

  static const char* value(const ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string id\n\
int32 measurement_image_border\n\
";
  }

  static const char* value(const ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.measurement_image_border);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEntityInfoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ed_gui_server::GetEntityInfoRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "measurement_image_border: ";
    Printer<int32_t>::stream(s, indent + "  ", v.measurement_image_border);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_GETENTITYINFOREQUEST_H
