// Generated by gencpp from file ed_gui_server/Interact.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_INTERACT_H
#define ED_GUI_SERVER_MESSAGE_INTERACT_H

#include <ros/service_traits.h>


#include <ed_gui_server/InteractRequest.h>
#include <ed_gui_server/InteractResponse.h>


namespace ed_gui_server
{

struct Interact
{

typedef InteractRequest Request;
typedef InteractResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Interact
} // namespace ed_gui_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ed_gui_server::Interact > {
  static const char* value()
  {
    return "ecc6574037514178d24baf752df47209";
  }

  static const char* value(const ::ed_gui_server::Interact&) { return value(); }
};

template<>
struct DataType< ::ed_gui_server::Interact > {
  static const char* value()
  {
    return "ed_gui_server/Interact";
  }

  static const char* value(const ::ed_gui_server::Interact&) { return value(); }
};


// service_traits::MD5Sum< ::ed_gui_server::InteractRequest> should match 
// service_traits::MD5Sum< ::ed_gui_server::Interact > 
template<>
struct MD5Sum< ::ed_gui_server::InteractRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ed_gui_server::Interact >::value();
  }
  static const char* value(const ::ed_gui_server::InteractRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ed_gui_server::InteractRequest> should match 
// service_traits::DataType< ::ed_gui_server::Interact > 
template<>
struct DataType< ::ed_gui_server::InteractRequest>
{
  static const char* value()
  {
    return DataType< ::ed_gui_server::Interact >::value();
  }
  static const char* value(const ::ed_gui_server::InteractRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ed_gui_server::InteractResponse> should match 
// service_traits::MD5Sum< ::ed_gui_server::Interact > 
template<>
struct MD5Sum< ::ed_gui_server::InteractResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ed_gui_server::Interact >::value();
  }
  static const char* value(const ::ed_gui_server::InteractResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ed_gui_server::InteractResponse> should match 
// service_traits::DataType< ::ed_gui_server::Interact > 
template<>
struct DataType< ::ed_gui_server::InteractResponse>
{
  static const char* value()
  {
    return DataType< ::ed_gui_server::Interact >::value();
  }
  static const char* value(const ::ed_gui_server::InteractResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_INTERACT_H
