// Generated by gencpp from file ed_gui_server/objsPosVel.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_OBJSPOSVEL_H
#define ED_GUI_SERVER_MESSAGE_OBJSPOSVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ed_gui_server/objPosVel.h>

namespace ed_gui_server
{
template <class ContainerAllocator>
struct objsPosVel_
{
  typedef objsPosVel_<ContainerAllocator> Type;

  objsPosVel_()
    : header()
    , objects()  {
    }
  objsPosVel_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ed_gui_server::objPosVel_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ed_gui_server::objPosVel_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::ed_gui_server::objsPosVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ed_gui_server::objsPosVel_<ContainerAllocator> const> ConstPtr;

}; // struct objsPosVel_

typedef ::ed_gui_server::objsPosVel_<std::allocator<void> > objsPosVel;

typedef boost::shared_ptr< ::ed_gui_server::objsPosVel > objsPosVelPtr;
typedef boost::shared_ptr< ::ed_gui_server::objsPosVel const> objsPosVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ed_gui_server::objsPosVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ed_gui_server::objsPosVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ed_gui_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ed_gui_server': ['/home/gosse/ropod-project-software/catkin_workspace/src/functionalities/ED/ed_gui_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::objsPosVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::objsPosVel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::objsPosVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::objsPosVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::objsPosVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::objsPosVel_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ed_gui_server::objsPosVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8dbe030c0254dab8cae216502656db0";
  }

  static const char* value(const ::ed_gui_server::objsPosVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8dbe030c0254dabULL;
  static const uint64_t static_value2 = 0x8cae216502656db0ULL;
};

template<class ContainerAllocator>
struct DataType< ::ed_gui_server::objsPosVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed_gui_server/objsPosVel";
  }

  static const char* value(const ::ed_gui_server::objsPosVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ed_gui_server::objsPosVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
objPosVel[] objects\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ed_gui_server/objPosVel\n\
string ID\n\
rectangleProperties rectangle\n\
circleProperties circle\n\
\n\
================================================================================\n\
MSG: ed_gui_server/rectangleProperties\n\
float32 probability\n\
\n\
geometry_msgs/Pose pose\n\
float32 xPosStdDev\n\
float32 yPosStdDev\n\
float32 yawStdDev\n\
\n\
float32 width\n\
float32 depth\n\
float32 yaw\n\
\n\
float32 widthStdDev\n\
float32 depthStdDev\n\
\n\
geometry_msgs/Vector3 vel\n\
float32 yawVel\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: ed_gui_server/circleProperties\n\
float32 probability\n\
\n\
geometry_msgs/Pose pose\n\
float32 xPosStdDev\n\
float32 yPosStdDev\n\
\n\
float32 radius\n\
float32 radiusStdDev\n\
\n\
geometry_msgs/Vector3 vel\n\
";
  }

  static const char* value(const ::ed_gui_server::objsPosVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ed_gui_server::objsPosVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct objsPosVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ed_gui_server::objsPosVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ed_gui_server::objsPosVel_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ed_gui_server::objPosVel_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_OBJSPOSVEL_H
