// Generated by gencpp from file ed_gui_server/QueryMeshes.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_QUERYMESHES_H
#define ED_GUI_SERVER_MESSAGE_QUERYMESHES_H

#include <ros/service_traits.h>


#include <ed_gui_server/QueryMeshesRequest.h>
#include <ed_gui_server/QueryMeshesResponse.h>


namespace ed_gui_server
{

struct QueryMeshes
{

typedef QueryMeshesRequest Request;
typedef QueryMeshesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryMeshes
} // namespace ed_gui_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ed_gui_server::QueryMeshes > {
  static const char* value()
  {
    return "f27133411b9d66830d753dafbc468b27";
  }

  static const char* value(const ::ed_gui_server::QueryMeshes&) { return value(); }
};

template<>
struct DataType< ::ed_gui_server::QueryMeshes > {
  static const char* value()
  {
    return "ed_gui_server/QueryMeshes";
  }

  static const char* value(const ::ed_gui_server::QueryMeshes&) { return value(); }
};


// service_traits::MD5Sum< ::ed_gui_server::QueryMeshesRequest> should match 
// service_traits::MD5Sum< ::ed_gui_server::QueryMeshes > 
template<>
struct MD5Sum< ::ed_gui_server::QueryMeshesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ed_gui_server::QueryMeshes >::value();
  }
  static const char* value(const ::ed_gui_server::QueryMeshesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ed_gui_server::QueryMeshesRequest> should match 
// service_traits::DataType< ::ed_gui_server::QueryMeshes > 
template<>
struct DataType< ::ed_gui_server::QueryMeshesRequest>
{
  static const char* value()
  {
    return DataType< ::ed_gui_server::QueryMeshes >::value();
  }
  static const char* value(const ::ed_gui_server::QueryMeshesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ed_gui_server::QueryMeshesResponse> should match 
// service_traits::MD5Sum< ::ed_gui_server::QueryMeshes > 
template<>
struct MD5Sum< ::ed_gui_server::QueryMeshesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ed_gui_server::QueryMeshes >::value();
  }
  static const char* value(const ::ed_gui_server::QueryMeshesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ed_gui_server::QueryMeshesResponse> should match 
// service_traits::DataType< ::ed_gui_server::QueryMeshes > 
template<>
struct DataType< ::ed_gui_server::QueryMeshesResponse>
{
  static const char* value()
  {
    return DataType< ::ed_gui_server::QueryMeshes >::value();
  }
  static const char* value(const ::ed_gui_server::QueryMeshesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_QUERYMESHES_H
