// Generated by gencpp from file ed_gui_server/QueryEntitiesRequest.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_QUERYENTITIESREQUEST_H
#define ED_GUI_SERVER_MESSAGE_QUERYENTITIESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>
#include <geometry_msgs/Point32.h>

namespace ed_gui_server
{
template <class ContainerAllocator>
struct QueryEntitiesRequest_
{
  typedef QueryEntitiesRequest_<ContainerAllocator> Type;

  QueryEntitiesRequest_()
    : area_min()
    , area_max()  {
    }
  QueryEntitiesRequest_(const ContainerAllocator& _alloc)
    : area_min(_alloc)
    , area_max(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _area_min_type;
  _area_min_type area_min;

   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _area_max_type;
  _area_max_type area_max;





  typedef boost::shared_ptr< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QueryEntitiesRequest_

typedef ::ed_gui_server::QueryEntitiesRequest_<std::allocator<void> > QueryEntitiesRequest;

typedef boost::shared_ptr< ::ed_gui_server::QueryEntitiesRequest > QueryEntitiesRequestPtr;
typedef boost::shared_ptr< ::ed_gui_server::QueryEntitiesRequest const> QueryEntitiesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ed_gui_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ed_gui_server': ['/home/gosse/ropod-project-software/catkin_workspace/src/functionalities/ED/ed_gui_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f69750d5b808229c7cf85b1629f71144";
  }

  static const char* value(const ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf69750d5b808229cULL;
  static const uint64_t static_value2 = 0x7cf85b1629f71144ULL;
};

template<class ContainerAllocator>
struct DataType< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed_gui_server/QueryEntitiesRequest";
  }

  static const char* value(const ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Point32 area_min\n\
geometry_msgs/Point32 area_max\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area_min);
      stream.next(m.area_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryEntitiesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ed_gui_server::QueryEntitiesRequest_<ContainerAllocator>& v)
  {
    s << indent << "area_min: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.area_min);
    s << indent << "area_max: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.area_max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_QUERYENTITIESREQUEST_H
