// Generated by gencpp from file ed_gui_server/QueryMeshesResponse.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_QUERYMESHESRESPONSE_H
#define ED_GUI_SERVER_MESSAGE_QUERYMESHESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ed_gui_server/EntityMeshAndAreas.h>

namespace ed_gui_server
{
template <class ContainerAllocator>
struct QueryMeshesResponse_
{
  typedef QueryMeshesResponse_<ContainerAllocator> Type;

  QueryMeshesResponse_()
    : entity_geometries()
    , error_msg()  {
    }
  QueryMeshesResponse_(const ContainerAllocator& _alloc)
    : entity_geometries(_alloc)
    , error_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >::other >  _entity_geometries_type;
  _entity_geometries_type entity_geometries;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_msg_type;
  _error_msg_type error_msg;





  typedef boost::shared_ptr< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QueryMeshesResponse_

typedef ::ed_gui_server::QueryMeshesResponse_<std::allocator<void> > QueryMeshesResponse;

typedef boost::shared_ptr< ::ed_gui_server::QueryMeshesResponse > QueryMeshesResponsePtr;
typedef boost::shared_ptr< ::ed_gui_server::QueryMeshesResponse const> QueryMeshesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ed_gui_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ed_gui_server': ['/home/gosse/ropod-project-software/catkin_workspace/src/functionalities/ED/ed_gui_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "411ac55771c9f34ab382969a5e932222";
  }

  static const char* value(const ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x411ac55771c9f34aULL;
  static const uint64_t static_value2 = 0xb382969a5e932222ULL;
};

template<class ContainerAllocator>
struct DataType< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed_gui_server/QueryMeshesResponse";
  }

  static const char* value(const ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "EntityMeshAndAreas[] entity_geometries\n\
\n\
\n\
string error_msg\n\
\n\
\n\
================================================================================\n\
MSG: ed_gui_server/EntityMeshAndAreas\n\
string id\n\
Mesh mesh\n\
Area[] areas\n\
\n\
================================================================================\n\
MSG: ed_gui_server/Mesh\n\
# Mesh identifier\n\
uint32 revision\n\
\n\
# At the moment, only vertices are used. The triangles are described by 9 elements in the\n\
# vertices array (x1, y1, z1, x2, y2, z2, x3, y3, z3). The triangles array is NOT used.\n\
\n\
# (original method (NOT USED): List of vertices: each 3 elements describe (x, y, z) )\n\
float32[] vertices\n\
\n\
# (origin method (NOT USED) List of indices: each 3 indices describe one triangle, indexing the vertices given above)\n\
uint32[] triangles\n\
\n\
================================================================================\n\
MSG: ed_gui_server/Area\n\
string name\n\
Mesh mesh\n\
";
  }

  static const char* value(const ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.entity_geometries);
      stream.next(m.error_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryMeshesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ed_gui_server::QueryMeshesResponse_<ContainerAllocator>& v)
  {
    s << indent << "entity_geometries[]" << std::endl;
    for (size_t i = 0; i < v.entity_geometries.size(); ++i)
    {
      s << indent << "  entity_geometries[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ed_gui_server::EntityMeshAndAreas_<ContainerAllocator> >::stream(s, indent + "    ", v.entity_geometries[i]);
    }
    s << indent << "error_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_QUERYMESHESRESPONSE_H
