// Generated by gencpp from file ed_gui_server/QueryEntities.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_QUERYENTITIES_H
#define ED_GUI_SERVER_MESSAGE_QUERYENTITIES_H

#include <ros/service_traits.h>


#include <ed_gui_server/QueryEntitiesRequest.h>
#include <ed_gui_server/QueryEntitiesResponse.h>


namespace ed_gui_server
{

struct QueryEntities
{

typedef QueryEntitiesRequest Request;
typedef QueryEntitiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryEntities
} // namespace ed_gui_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ed_gui_server::QueryEntities > {
  static const char* value()
  {
    return "3832db39c935108b6a41c50567ccd948";
  }

  static const char* value(const ::ed_gui_server::QueryEntities&) { return value(); }
};

template<>
struct DataType< ::ed_gui_server::QueryEntities > {
  static const char* value()
  {
    return "ed_gui_server/QueryEntities";
  }

  static const char* value(const ::ed_gui_server::QueryEntities&) { return value(); }
};


// service_traits::MD5Sum< ::ed_gui_server::QueryEntitiesRequest> should match 
// service_traits::MD5Sum< ::ed_gui_server::QueryEntities > 
template<>
struct MD5Sum< ::ed_gui_server::QueryEntitiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ed_gui_server::QueryEntities >::value();
  }
  static const char* value(const ::ed_gui_server::QueryEntitiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ed_gui_server::QueryEntitiesRequest> should match 
// service_traits::DataType< ::ed_gui_server::QueryEntities > 
template<>
struct DataType< ::ed_gui_server::QueryEntitiesRequest>
{
  static const char* value()
  {
    return DataType< ::ed_gui_server::QueryEntities >::value();
  }
  static const char* value(const ::ed_gui_server::QueryEntitiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ed_gui_server::QueryEntitiesResponse> should match 
// service_traits::MD5Sum< ::ed_gui_server::QueryEntities > 
template<>
struct MD5Sum< ::ed_gui_server::QueryEntitiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ed_gui_server::QueryEntities >::value();
  }
  static const char* value(const ::ed_gui_server::QueryEntitiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ed_gui_server::QueryEntitiesResponse> should match 
// service_traits::DataType< ::ed_gui_server::QueryEntities > 
template<>
struct DataType< ::ed_gui_server::QueryEntitiesResponse>
{
  static const char* value()
  {
    return DataType< ::ed_gui_server::QueryEntities >::value();
  }
  static const char* value(const ::ed_gui_server::QueryEntitiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_QUERYENTITIES_H
