// Generated by gencpp from file ed_gui_server/rectangleProperties.msg
// DO NOT EDIT!


#ifndef ED_GUI_SERVER_MESSAGE_RECTANGLEPROPERTIES_H
#define ED_GUI_SERVER_MESSAGE_RECTANGLEPROPERTIES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Vector3.h>

namespace ed_gui_server
{
template <class ContainerAllocator>
struct rectangleProperties_
{
  typedef rectangleProperties_<ContainerAllocator> Type;

  rectangleProperties_()
    : probability(0.0)
    , pose()
    , xPosStdDev(0.0)
    , yPosStdDev(0.0)
    , yawStdDev(0.0)
    , width(0.0)
    , depth(0.0)
    , yaw(0.0)
    , widthStdDev(0.0)
    , depthStdDev(0.0)
    , vel()
    , yawVel(0.0)  {
    }
  rectangleProperties_(const ContainerAllocator& _alloc)
    : probability(0.0)
    , pose(_alloc)
    , xPosStdDev(0.0)
    , yPosStdDev(0.0)
    , yawStdDev(0.0)
    , width(0.0)
    , depth(0.0)
    , yaw(0.0)
    , widthStdDev(0.0)
    , depthStdDev(0.0)
    , vel(_alloc)
    , yawVel(0.0)  {
  (void)_alloc;
    }



   typedef float _probability_type;
  _probability_type probability;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _xPosStdDev_type;
  _xPosStdDev_type xPosStdDev;

   typedef float _yPosStdDev_type;
  _yPosStdDev_type yPosStdDev;

   typedef float _yawStdDev_type;
  _yawStdDev_type yawStdDev;

   typedef float _width_type;
  _width_type width;

   typedef float _depth_type;
  _depth_type depth;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _widthStdDev_type;
  _widthStdDev_type widthStdDev;

   typedef float _depthStdDev_type;
  _depthStdDev_type depthStdDev;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _vel_type;
  _vel_type vel;

   typedef float _yawVel_type;
  _yawVel_type yawVel;





  typedef boost::shared_ptr< ::ed_gui_server::rectangleProperties_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ed_gui_server::rectangleProperties_<ContainerAllocator> const> ConstPtr;

}; // struct rectangleProperties_

typedef ::ed_gui_server::rectangleProperties_<std::allocator<void> > rectangleProperties;

typedef boost::shared_ptr< ::ed_gui_server::rectangleProperties > rectanglePropertiesPtr;
typedef boost::shared_ptr< ::ed_gui_server::rectangleProperties const> rectanglePropertiesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ed_gui_server::rectangleProperties_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ed_gui_server::rectangleProperties_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ed_gui_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'ed_gui_server': ['/home/gosse/ropod-project-software/catkin_workspace/src/functionalities/ED/ed_gui_server/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::rectangleProperties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ed_gui_server::rectangleProperties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::rectangleProperties_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ed_gui_server::rectangleProperties_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::rectangleProperties_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ed_gui_server::rectangleProperties_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ed_gui_server::rectangleProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fbe313d52ce9ce9f68498aaf6e07ecb9";
  }

  static const char* value(const ::ed_gui_server::rectangleProperties_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfbe313d52ce9ce9fULL;
  static const uint64_t static_value2 = 0x68498aaf6e07ecb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::ed_gui_server::rectangleProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed_gui_server/rectangleProperties";
  }

  static const char* value(const ::ed_gui_server::rectangleProperties_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ed_gui_server::rectangleProperties_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 probability\n\
\n\
geometry_msgs/Pose pose\n\
float32 xPosStdDev\n\
float32 yPosStdDev\n\
float32 yawStdDev\n\
\n\
float32 width\n\
float32 depth\n\
float32 yaw\n\
\n\
float32 widthStdDev\n\
float32 depthStdDev\n\
\n\
geometry_msgs/Vector3 vel\n\
float32 yawVel\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::ed_gui_server::rectangleProperties_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ed_gui_server::rectangleProperties_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.probability);
      stream.next(m.pose);
      stream.next(m.xPosStdDev);
      stream.next(m.yPosStdDev);
      stream.next(m.yawStdDev);
      stream.next(m.width);
      stream.next(m.depth);
      stream.next(m.yaw);
      stream.next(m.widthStdDev);
      stream.next(m.depthStdDev);
      stream.next(m.vel);
      stream.next(m.yawVel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rectangleProperties_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ed_gui_server::rectangleProperties_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ed_gui_server::rectangleProperties_<ContainerAllocator>& v)
  {
    s << indent << "probability: ";
    Printer<float>::stream(s, indent + "  ", v.probability);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "xPosStdDev: ";
    Printer<float>::stream(s, indent + "  ", v.xPosStdDev);
    s << indent << "yPosStdDev: ";
    Printer<float>::stream(s, indent + "  ", v.yPosStdDev);
    s << indent << "yawStdDev: ";
    Printer<float>::stream(s, indent + "  ", v.yawStdDev);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "widthStdDev: ";
    Printer<float>::stream(s, indent + "  ", v.widthStdDev);
    s << indent << "depthStdDev: ";
    Printer<float>::stream(s, indent + "  ", v.depthStdDev);
    s << indent << "vel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.vel);
    s << indent << "yawVel: ";
    Printer<float>::stream(s, indent + "  ", v.yawVel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ED_GUI_SERVER_MESSAGE_RECTANGLEPROPERTIES_H
